import type { ItineraryPlan } from '../types/itinerary';

export const PARIS_DEMO_PLAN: ItineraryPlan = {
  id: 'plan_demo_paris',
  title: '3-Day Romantic & Cultural Paris Gateway',
  destination: 'Paris, France',
  summary: 'A balanced blend of iconic landmarks, hidden Montmartre cafes, world-class art galleries, and serene Seine river cruising.',
  durationDays: 3,
  pace: 'balanced',
  travelerStyle: 'Cultural Explorer',
  createdAt: new Date().toISOString(),
  days: [
    {
      dayNumber: 1,
      theme: 'Classic Paris Icons & Seine Sunset',
      stops: [
        {
          id: 'p1_1',
          time: '09:00 AM',
          activity: 'Eiffel Tower & Champ de Mars',
          description: 'Early arrival at Trocadéro Gardens for scenic photos followed by summit access.',
          location: 'Champ de Mars, 5 Avenue Anatole France',
          estimatedCost: 32,
          category: 'sightseeing',
          completed: false,
          notes: 'Pre-book online tickets to skip queue',
        },
        {
          id: 'p1_2',
          time: '01:00 PM',
          activity: 'Lunch at Carette',
          description: 'Famous for hot chocolate, fresh pastries, and artisanal quiche on Place des Vosges.',
          location: '25 Place des Vosges',
          estimatedCost: 28,
          category: 'food',
          completed: false,
        },
        {
          id: 'p1_3',
          time: '03:30 PM',
          activity: 'Musée d\'Orsay Art Exploration',
          description: 'Immerse in impressionist masterpieces by Monet, Van Gogh, and Degas inside a grand railway station.',
          location: '1 Rue de la Légion d\'Honneur',
          estimatedCost: 16,
          category: 'culture',
          completed: false,
        },
        {
          id: 'p1_4',
          time: '07:30 PM',
          activity: 'Sunset Seine River Dinner Cruise',
          description: 'Glide past illuminated monuments with live accordion music and french wine.',
          location: 'Port de la Bourdonnais',
          estimatedCost: 65,
          category: 'relax',
          completed: false,
        },
      ],
    },
    {
      dayNumber: 2,
      theme: 'Bohemian Montmartre & Historic Le Marais',
      stops: [
        {
          id: 'p2_1',
          time: '09:30 AM',
          activity: 'Sacré-Cœur Basilica & Artists Square',
          description: 'Panoramic skyline view over Paris followed by street portraits at Place du Tertre.',
          location: '35 Rue du Chevalier de la Barre',
          estimatedCost: 0,
          category: 'sightseeing',
          completed: false,
        },
        {
          id: 'p2_2',
          time: '12:30 PM',
          activity: 'Artisanal Bakery Crawl & Bistro Lunch',
          description: 'Fresh warm baguettes, escargot, and duck confit at Le Consulat.',
          location: '18 Rue Norvins',
          estimatedCost: 35,
          category: 'food',
          completed: false,
        },
        {
          id: 'p2_3',
          time: '04:00 PM',
          activity: 'Boutique Shopping in Le Marais',
          description: 'Explore vintage clothing stores, concept shops, and hidden courtyards.',
          location: 'Rue des Francs-Bourgeois',
          estimatedCost: 50,
          category: 'shopping',
          completed: false,
        },
        {
          id: 'p2_4',
          time: '09:00 PM',
          activity: 'Jazz Night at Le Caveau de la Huchette',
          description: 'Historic subterranean medieval cellar jazz club.',
          location: '5 Rue de la Huchette',
          estimatedCost: 20,
          category: 'nightlife',
          completed: false,
        },
      ],
    },
    {
      dayNumber: 3,
      theme: 'Louvre Treasures & Palais Royal Serenity',
      stops: [
        {
          id: 'p3_1',
          time: '09:00 AM',
          activity: 'Louvre Museum Highlight Tour',
          description: 'View the Mona Lisa, Venus de Milo, and Winged Victory.',
          location: 'Rue de Rivoli',
          estimatedCost: 22,
          category: 'culture',
          completed: false,
        },
        {
          id: 'p3_2',
          time: '01:30 PM',
          activity: 'Palais-Royal Gardens Picnic',
          description: 'Relax among striped Buren columns with macarons from Pierre Hermé.',
          location: '8 Rue de Montpensier',
          estimatedCost: 18,
          category: 'relax',
          completed: false,
        },
        {
          id: 'p3_3',
          time: '05:00 PM',
          activity: 'Sainte-Chapelle Stained Glass Marvel',
          description: 'Marvel at 1,113 dramatic 13th-century stained glass windows.',
          location: '10 Boulevard du Palais',
          estimatedCost: 13,
          category: 'sightseeing',
          completed: false,
        },
      ],
    },
  ],
  budget: {
    currency: 'EUR',
    currencySymbol: '€',
    totalEstimated: 320,
    budgetTip: 'Buy Navigo Pass for unlimited Metro travel to save on transport.',
    categories: [
      { category: 'Food & Dining', amount: 120, percentage: 37, color: '#f59e0b' },
      { category: 'Attractions & Tours', amount: 105, percentage: 33, color: '#6366f1' },
      { category: 'Transport', amount: 35, percentage: 11, color: '#10b981' },
      { category: 'Nightlife & Drinks', amount: 60, percentage: 19, color: '#ec4899' },
    ],
  },
  packingChecklist: [
    {
      category: 'Travel Documents & Tech',
      items: [
        { id: 'pk_1', text: 'Passport & Visa Copies', checked: true, essential: true },
        { id: 'pk_2', text: 'EU Adapter Plug (Type C/E)', checked: false, essential: true },
        { id: 'pk_3', text: 'Powerbank & Charging Cables', checked: true, essential: false },
      ],
    },
    {
      category: 'Clothing & Comfort',
      items: [
        { id: 'pk_4', text: 'Comfortable Leather Walking Shoes', checked: true, essential: true },
        { id: 'pk_5', text: 'Light Trench Coat or Jacket', checked: false, essential: true },
        { id: 'pk_6', text: 'Stylish Evening Outfit for Bistro', checked: false, essential: false },
      ],
    },
    {
      category: 'Toiletries & Essentials',
      items: [
        { id: 'pk_7', text: 'Travel-size Sunscreen & Moisturizer', checked: true, essential: false },
        { id: 'pk_8', text: 'Prescription Medication', checked: true, essential: true },
      ],
    },
  ],
  highlights: [
    {
      id: 'hl_1',
      title: 'Metro Navigation Tip',
      category: 'tip',
      description: 'Keep your metro ticket until you exit the station; random ticket checks occur frequently.',
      tag: 'Transport',
    },
    {
      id: 'hl_2',
      title: 'Authentic Croissants',
      category: 'food',
      description: 'Look for "Boulangerie Artisanale" signage. Machines-made pastries lack the crispy butter layers!',
      tag: 'Foodie',
    },
    {
      id: 'hl_3',
      title: 'Best Photo Spot',
      category: 'photo',
      description: 'Rue de l\'Université offers an unobstructed, fairy-tale view right up to the Eiffel Tower base.',
      tag: 'Instagram',
    },
    {
      id: 'hl_4',
      title: 'Cultural Etiquette',
      category: 'culture',
      description: 'Always greet shopkeepers with a friendly "Bonjour Madame/Monsieur" when entering.',
      tag: 'Etiquette',
    },
  ],
};

export const TOKYO_DEMO_PLAN: ItineraryPlan = {
  id: 'plan_demo_tokyo',
  title: '4-Day Neon & Tradition Tokyo Experience',
  destination: 'Tokyo, Japan',
  summary: 'Immerse in futuristic Shibuya neon lights, ancient Asakusa shrines, street food, and peaceful gardens.',
  durationDays: 4,
  pace: 'fast-paced',
  travelerStyle: 'Urban Adventurer',
  createdAt: new Date().toISOString(),
  days: [
    {
      dayNumber: 1,
      theme: 'Ancient Shrines & Culinary Asakusa',
      stops: [
        {
          id: 'tk1_1',
          time: '08:30 AM',
          activity: 'Senso-ji Temple & Nakamise Street',
          description: 'Tokyo\'s oldest Buddhist temple. Walk through Kaminarimon Gate.',
          location: '2 Chome-3-1 Asakusa, Taito City',
          estimatedCost: 0,
          category: 'culture',
          completed: false,
        },
        {
          id: 'tk1_2',
          time: '12:00 PM',
          activity: 'Ramen Street at Tokyo Station',
          description: 'Savory rich Tonkotsu and Tsukemen dipped ramen.',
          location: 'Tokyo Station Underground',
          estimatedCost: 12,
          category: 'food',
          completed: false,
        },
        {
          id: 'tk1_3',
          time: '03:00 PM',
          activity: 'Akihabara Electric Town',
          description: 'Explore retro arcade centers, manga shops, and gadget stores.',
          location: 'Sotokanda, Chiyoda City',
          estimatedCost: 25,
          category: 'shopping',
          completed: false,
        },
      ],
    },
    {
      dayNumber: 2,
      theme: 'Shibuya Crossing & Harajuku Trends',
      stops: [
        {
          id: 'tk2_1',
          time: '09:30 AM',
          activity: 'Meiji Jingu Shrine Forest Walk',
          description: 'Peaceful wooden torii gate walk in sacred evergreen forest.',
          location: '1-1 Yoyogikamizonocho, Shibuya',
          estimatedCost: 0,
          category: 'relax',
          completed: false,
        },
        {
          id: 'tk2_2',
          time: '01:00 PM',
          activity: 'Takeshita Street Crepes & Fashion',
          description: 'Harajuku street culture, colorful cotton candy, and youth fashion.',
          location: 'Jingumae, Shibuya',
          estimatedCost: 15,
          category: 'food',
          completed: false,
        },
        {
          id: 'tk2_3',
          time: '05:30 PM',
          activity: 'Shibuya Sky Observation Deck',
          description: '360-degree panoramic open-air roof deck overlooking Shibuya Crossing.',
          location: '2 Chome-24-12 Shibuya',
          estimatedCost: 20,
          category: 'sightseeing',
          completed: false,
        },
      ],
    },
  ],
  budget: {
    currency: 'JPY',
    currencySymbol: '¥',
    totalEstimated: 48000,
    budgetTip: 'Get a Suica or Pasmo IC card for easy train taps and convenience store payment.',
    categories: [
      { category: 'Food & Dining', amount: 18000, percentage: 38, color: '#f59e0b' },
      { category: 'Transport (IC Rail)', amount: 8000, percentage: 17, color: '#10b981' },
      { category: 'Attractions', amount: 12000, percentage: 25, color: '#6366f1' },
      { category: 'Shopping & Souvenirs', amount: 10000, percentage: 20, color: '#ec4899' },
    ],
  },
  packingChecklist: [
    {
      category: 'Essentials',
      items: [
        { id: 'tk_pk1', text: 'Pasmo/Suica Card on Apple Wallet', checked: true, essential: true },
        { id: 'tk_pk2', text: 'Pocket Wi-Fi or e-SIM', checked: true, essential: true },
        { id: 'tk_pk3', text: 'Slip-on Shoes for Temples', checked: false, essential: true },
      ],
    },
  ],
  highlights: [
    {
      id: 'tk_hl1',
      title: 'Cash is Still King',
      category: 'tip',
      description: 'Many small ramen shops and street vendors only accept 1,000 yen bills or coins.',
      tag: 'Finance',
    },
    {
      id: 'tk_hl2',
      title: 'Convenience Stores',
      category: 'food',
      description: '7-Eleven, Lawson, and FamilyMart offer chef-grade egg sandwiches, Onigiri, and hot fried chicken.',
      tag: 'Culinary',
    },
  ],
};
